/*
 *  ***************************************************************
 *     Polytechnic University of Puerto Rico                      *
 *     Electrical & Computer Engineering and                      *
 *          Computer Science Department                           *
 *                                                                *
 *      Student: Jorge Carrillo Rodriguez                         *
 *                ID: #74186                                      *
 *  ***************************************************************
 */
package edu.pupr.temperaturegui;

import java.awt.event.ItemEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class TemperatureConverter extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureConverter
     */
    public TemperatureConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        Label1 = new javax.swing.JLabel();
        temperature_txt = new javax.swing.JTextField();
        buttonCelsius = new javax.swing.JRadioButton();
        buttonFahrenheit = new javax.swing.JRadioButton();
        buttonResult = new javax.swing.JButton();
        result_lbl = new javax.swing.JLabel();
        tempResult_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Convertion");
        setBackground(new java.awt.Color(51, 51, 51));

        Label1.setText("Temperature:");

        temperature_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        temperature_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                temperature_txtFocusLost(evt);
            }
        });
        temperature_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperature_txtActionPerformed(evt);
            }
        });

        buttonGroup.add(buttonCelsius);
        buttonCelsius.setSelected(true);
        buttonCelsius.setText("To Celsius");
        buttonCelsius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                buttonCelsiusItemStateChanged(evt);
            }
        });

        buttonGroup.add(buttonFahrenheit);
        buttonFahrenheit.setText("To Fahrenheit");
        buttonFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFahrenheitActionPerformed(evt);
            }
        });

        buttonResult.setText("Show Result");
        buttonResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResultActionPerformed(evt);
            }
        });

        result_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        result_lbl.setText("Result:");

        tempResult_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tempResult_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperature_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCelsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFahrenheit)
                        .addGap(18, 18, 18)
                        .addComponent(buttonResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(result_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(tempResult_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label1)
                            .addComponent(temperature_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCelsius)
                            .addComponent(buttonFahrenheit)
                            .addComponent(buttonResult))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(result_lbl)
                    .addComponent(tempResult_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperature_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperature_txtActionPerformed

        
    }//GEN-LAST:event_temperature_txtActionPerformed

    private void buttonFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFahrenheitActionPerformed
       
    }//GEN-LAST:event_buttonFahrenheitActionPerformed

    private void buttonCelsiusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_buttonCelsiusItemStateChanged
        
     
       
    }//GEN-LAST:event_buttonCelsiusItemStateChanged

    private void temperature_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temperature_txtFocusLost
       
                
                try{
                    double number = Double.parseDouble(temperature_txt.getText());
                    
                }
                    catch(NumberFormatException exception) {
                        JOptionPane.showMessageDialog(rootPane, "Wrong Input");
                        temperature_txt.requestFocus();
                    }                      
    }//GEN-LAST:event_temperature_txtFocusLost

    
    private void buttonResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResultActionPerformed
   
               if(buttonCelsius.isSelected() )
                { 
            
                   toCelsius();
                
                }else
                {
                    if(buttonFahrenheit.isSelected() )
                    {
                        toFahrenheit();
                      
                    }
                }      
    }//GEN-LAST:event_buttonResultActionPerformed

    /**
     * Converts Temperature To Celsius
     * and Sets The Value To The Temperature Result Label
     */
    public void toCelsius() {
        
        double celsius = Double.parseDouble(temperature_txt.getText());
        DecimalFormat df = new DecimalFormat("#.##");
        double temp;
        
        temp = 5.0/9.0 * (celsius - 32);
        
        tempResult_lbl.setText(df.format(temp) + " C°");
           
    }
    
     /**
     * Converts Temperature To Fahrenheit
     * and Sets The Value To The Temperature Result Label
     */
    public void toFahrenheit() {
       
        double fahrenheit = Double.parseDouble(temperature_txt.getText());
        DecimalFormat df = new DecimalFormat("#.##");
        double temp;
        
        temp = 9.0/5.0 * fahrenheit + 32;
        
        tempResult_lbl.setText(df.format(temp) + " F°");
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JRadioButton buttonCelsius;
    private javax.swing.JRadioButton buttonFahrenheit;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonResult;
    private javax.swing.JLabel result_lbl;
    private javax.swing.JLabel tempResult_lbl;
    private javax.swing.JTextField temperature_txt;
    // End of variables declaration//GEN-END:variables
}
